split release to 2 phases : prepare and release (#77)
Signed-off-by: Radouane Khouadri <redouane.khouadri_externe@rte-france.com>

diff --git a/.github/workflows/prepare-release.yml b/.github/workflows/prepare-release.yml
--- a/.github/workflows/prepare-release.yml
+++ b/.github/workflows/prepare-release.yml
@@ -4,13 +4,10 @@ on:
       githubappId:
         required: true
         type: string
-      dockerImage:
-        required: true
-        type: string
-      dockerUsername:
-        required: true
-        type: string
       releaseVersion:
+        required: true
+        type: string
+      gitReference:
         required: true
         type: string
       environment:
@@ -19,8 +16,6 @@ on:
         type: string
     secrets:
       VERSIONBUMP_GHAPP_PRIVATE_KEY:
-        required: true
-      DOCKERHUB_TOKEN:
         required: true
 
 jobs:
@@ -67,6 +62,9 @@ jobs:
         env:
           GH_TOKEN: ${{ steps.app-token.outputs.token }}
           RUNGHA_APP_SLUG: ${{ steps.app-token.outputs.app-slug }} # just for defense against script injection
+      # git user not used normally anymore because we use the github commit API
+      # to create the commits, but keep this anyway just in case. We do get the
+      # exact same value as the one github uses for creating the signed commits.
       - name: Setup git user
         run: |
           git config --global user.name "${RUNGHA_APP_SLUG}[bot]"
@@ -100,36 +98,83 @@ jobs:
         run: |
           if git ls-remote --quiet --exit-code origin "refs/heads/release-$RUNGHA_RELEASE_VERSION" >/dev/null 2>&1
           then
-            echo "Release branch exists, proceeding"
-          else
-            echo "ERROR: Release branch release-$RUNGHA_RELEASE_VERSION does not exist, run prepare-release first"
+            echo "ERROR: Release $RUNGHA_RELEASE_VERSION already exists"
             exit 1
+          else
+            echo "Release $RUNGHA_RELEASE_VERSION doesn't exist, it will be performed"
           fi
         env:
           RUNGHA_RELEASE_VERSION: ${{ inputs.releaseVersion }} # just for defense against script injection
 
-      - name: Checkout with new branch
+      # TODO deduplicate this code when github actions allows to easily share a script used
+      # by reusable workflows. Currently only the workflow file is checked out at the caller
+      # There are no good workarounds to checkout a companion file (script or composite action)
+      - name: Check if gitReference is merged in main
         run: |
-          git checkout "release-v${GITHUB_MAJOR_VERSION}.${GITHUB_MINOR_VERSION}"
+          # needs fetch-depth: 0
+          # This ensures that only reviewed commits can be released because
+          # we require reviews and pull requests to allow to merge in main.
+          if ! main_contains=$(git branch -r --format='%(refname:short)' --contains "$RUNGHA_GIT_REFERENCE" origin/main); then
+            echo "ERROR checking whether gitRef $RUNGHA_GIT_REFERENCE is merged in main or not"
+            exit 1
+          elif [ -z "$main_contains" ]; then
+            echo "ERROR: gitRef $RUNGHA_GIT_REFERENCE not merged in main"
+            exit 1
+          else
+            echo "gitRef $RUNGHA_GIT_REFERENCE merged in main, release will be performed"
+          fi
+        env:
+          RUNGHA_GIT_REFERENCE: ${{ inputs.gitReference }} # just for defense against script injection
 
-      - name: Create tag
+      # TODO deduplicate this code when github actions allows to easily share a script used
+      # by reusable workflows. Currently only the workflow file is checked out at the caller
+      # There are no good workarounds to checkout a companion file (script or composite action)
+      - name: Check if gitReference is missing already released commits
         run: |
-          git tag "v$GITHUB_SHORT_VERSION"
+          # The following block ensures that the new release will not omit
+          # commits that were already released. If this case was allowed, then
+          # it would for instance be possible to release a new version without
+          # some security fixes. For linear histories, this would happen when
+          # rereleasing an old commit as a new version. For non linear histories,
+          # this could additionally happen when releasing a new commit (subsequently
+          # merged in main) but that branches off of old commits (or even unrelated histories).
+          # If the code that finds existing releases fails and doesn't find anything, it
+          # could be the first release, or it could be that there is a bug or exploit. In
+          # this case, instead of allowing to release anything, we just allow to release the
+          # tip of main (allowing to release anything else would also allow to omit commits).
+          # NOTE: needs fetch-depth: 0
+          all_release_tags=$(git tag --list 'v[0-9]*')
+          if [[ -z "$all_release_tags" ]]; then
+            echo "WARN no existing release tags found, is this the first release?"
+            if ! git_reference_parsed=$(git rev-parse "$RUNGHA_GIT_REFERENCE"); then
+              echo "ERROR rev-parsing gitRef $RUNGHA_GIT_REFERENCE"
+              exit 1
+            fi
+            if ! main_parsed=$(git rev-parse origin/main); then
+              echo "ERROR rev-parsing origin/main"
+              exit 1
+            fi
+            if [[ -n "$git_reference_parsed" && "$git_reference_parsed" != "$main_parsed" ]]; then
+              echo "ERROR: No existing release found, must release the tip of main $main_parsed but got $git_reference_parsed"
+              exit 1
+            else
+              echo "gitRef $RUNGHA_GIT_REFERENCE is tip of main, release will be performed"
+            fi
+          else
+            latest_main_release=$(git merge-base main $all_release_tags)
+            if ! git merge-base --is-ancestor "$latest_main_release" "$RUNGHA_GIT_REFERENCE"; then
+              echo "ERROR gitRef $RUNGHA_GIT_REFERENCE is not a descendant of the latest released commit $latest_main_release"
+              exit 1
+            else
+              echo "gitRef $RUNGHA_GIT_REFERENCE descends from previous releases, release will be performed"
+            fi
+          fi
+        env:
+          RUNGHA_GIT_REFERENCE: ${{ inputs.gitReference }} # just for defense against script injection
 
-      - name: Login to Docker Hub
-        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4.0.0
-        with:
-          username: ${{ inputs.dockerUsername }}
-          password: ${{ secrets.DOCKERHUB_TOKEN }}
-
-      - name: Build and publish Docker image
-        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6.19.2
-        with:
-          context: .
-          push: true
-          tags: ${{ inputs.dockerImage }}:${{ env.GITHUB_SHORT_VERSION }}
-
-      - name: Push release branch and tag
+      - name: Checkout with new branch, push tmp branch for signed commit
         run: |
+          git checkout -b "release-v${GITHUB_MAJOR_VERSION}.${GITHUB_MINOR_VERSION}" "$RUNGHA_GIT_REFERENCE"
           git push origin "release-v${GITHUB_MAJOR_VERSION}.${GITHUB_MINOR_VERSION}"
-          git push origin "v$GITHUB_SHORT_VERSION"
+        env:
+          RUNGHA_GIT_REFERENCE: ${{ inputs.gitReference }} # just for defense against script injection
